myname=vim

all: build_init dep build install

build_init: 
	@echo Installing $(myname)

dep:
	@echo $(myname): installing dependencies

build:
	@echo $(myname): building

install:
	@echo $(myname): installing
