myname=vim

all: init dep build install finish

init: 
	@echo Installing $(myname)

dep:
	@echo $(myname): installing dependencies

build:
	@echo $(myname): building

install:
	@echo $(myname): installing

finish:
	@echo

